### PR TITLE
Fix issue with class based views

### LINKED ISSUE #20: Expose aiohttp application to rpc function
I've noticed (supposingly) a design issue with RPC handlers.

I've got an app, where I attach some interfaces to globally accessible app object. I need to access app from within the handler therefore.
But I get only `request` as an input and that's it.
I guess, it is possible to retrieve app via `request.http_request.app`, but that's too verbose and annoying to repeat over and over in every each handler. Also using `@unpack_request_args` hides access to `request` at all.

Currently I'm thinking about introducing some kind of Class-Based "views" concept.

@fscherf do you have any additional ideas regarding this?

### PR DESCRIPTION
**Pull request by ZhukovGreen**
When decorator `unpack_request_args` was applied to a class based views there was an error, when dispatching args to `origin_rpc_method`. 

Fix #20

### CODE REVIEW

**Comment by fscherf** [comment]
I am sorry it took me so long but the checks failed and i thought you would send a new version.
I tested your patches local and merged all ``unpack_request_args`` related. For the client patches i would ask you to send a separate pull request.

**Comment by ZhukovGreen** [comment]
Yeah, I'll redo it a bit.

**Comment by ZhukovGreen** [comment]
Let's close this MR and I'll make the new one, which will be improving the usage of the context manager

**Comment by fscherf** [comment]
Ack!

**Pull request closed without merging**
