### PR TITLE
Update aiohttp version constraint to 3.4

### PR DESCRIPTION
**Pull request by Tobotimus**
The aiohttp dependency hasn't been updated for some time. I've pushed it up to <3.4 as aiohttp's latest version is currently 3.3.

Thanks for the work you guys do on this library!

### CODE REVIEW

**Comment by fscherf** [comment]
Hi @Tobotimus :)

thx for testing and contributing, i will release v0.10.2 today.

**Comment by fscherf** [comment]
Huh! When you pull-requested aiohttp 3.2.1 was out and all tests run successfully on travis.
Unfortunately only minutes after aiohttp 3.2.2 was released, and now fail all pypy jobs.

@Tobotimus: any idieas?

@webknjaz: you submitted the pypy stages. any ideas?

**Comment by webknjaz** [comment]
I'm not sure, I've recently updated underlying http parsing library in aiohttp, so it *might be* the cause.

**Comment by Tobotimus** [comment]
To be completely honest I've never even used pypy, but I can confirm by running the tests on my local machine that rolling back to aiohttp 3.3.1 allows the tests to pass on pypy3.5-5.8.0. I will open a pull request setting the version contraint to <3.3.2 as a possible short term solution :smiley:

**Comment by webknjaz** [comment]
I think, this needs an issue in aiohttp upstream. As for this repo, let's also update interpreter to pypy3.5-5.10.1

**Comment by webknjaz** [comment]
It looks like the only difference is in proxy connection: https://github.com/aio-libs/aiohttp/compare/v3.3.1...v3.3.2#diff-7f25afde79f309e2f8722c26cf1f10adR901

**Comment by fscherf** [comment]
@webknjaz: when i click on your  link github says:

```
There isn’t anything to compare.
We couldn’t figure out how to compare these references, do they point to valid commits?
```

Anyway. Can you fix it?

**Comment by webknjaz** [comment]
oh, github broke the hash from that link: https://github.com/aio-libs/aiohttp/compare/v3.3.1...v3.3.2 #diff-7f25afde79f309e2f8722c26cf1f10adR901

**Comment by webknjaz** [comment]
I don't know whether I can fix it. Since it refers `*.pyx` (Cython module) it's related to compiled http client extension, it's not really intended to work on PyPy (nobody took effort into it), so it should be fine with `AIOHTTP_NO_EXTENSIONS=1` env var.
On the other hand, it's better to be fixed, so upstream ticket would be needed.

**Comment by Tobotimus** [comment]
@webknjaz your suggestion to update the CI's pypy version to 5.10.1 actually allows the tests to pass with aiohttp 3.3.2.

@fscherf thoughts?

**Comment by webknjaz** [comment]
Alright. That's it. I'm keeping PyPy in CI in projects I maintain at the latest version. So I'd not worry about upgrading just version of it unless you specifically target this interpreter.

**Comment by fscherf** [comment]
@webknjaz 
@Tobotimus 

Ouh! :) You guys are right, this does the trick:

```diff
commit a3223550647cc7e1711f84c186848af4f54b34fe
Author: Florian Scherf <f.scherf@pengutronix.de>
Date:   Fri Jun 15 10:41:37 2018 +0200

    RFC: travis: update pypy3
    
    Signed-off-by: Florian Scherf <f.scherf@pengutronix.de>

diff --git a/.travis.yml b/.travis.yml
index 9a02eec26868..7badc661c9db 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -14,7 +14,7 @@ stages:
 python:
 - 3.5
 - &mainstream_python 3.6
-- &pypy3 pypy3.5-5.8.0
+- &pypy3 pypy3.5-5.10.1
 
 env:
 - ""
```

https://travis-ci.org/pengutronix/aiohttp-json-rpc/builds/392618524

Should this be a static version number like now or a version range? I am pretty warily on version ranges now :D

**Comment by webknjaz** [comment]
It's not a version range. it's a single version. `3.5` is a branch of PyPy supporting Python 3.5 (with some of the features from 3.6) and 5.10.1 is a version on that branch.

**Comment by fscherf** [comment]
FTR: this is fixed and merged in #28

**Pull request merged**
