### PR TITLE
Update release scripts to have modern setuptools

### PR DESCRIPTION
**Pull request by webknjaz**
Ref #10

### CODE REVIEW

**Comment by fscherf** [comment]
ah ok. Why does it use development mode?

**Comment by webknjaz** [comment]
Feel free to try removing it, it fails otherwise on my laptop, but that might be something in my env

**Comment by fscherf** [comment]
i removed the development mode and added twine to the dependencies. it seems to work, i would merge it like this

**Comment by fscherf** [comment]
i think we can remove the makefile when it runs in tox

**Comment by webknjaz** [comment]
Sounds reasonable, feel free to do this yourself, I'm AFK now.

**Comment by fscherf** [comment]
aaaahhh got it! you have to remove the classifiers from the setup.py to make setuptools use the classifiers defined in the setup.cfg.

Thanks for your great work and patience :) i released v0.8.4.3 now, i hope you are happy with it

**Comment by webknjaz** [comment]
Yeah, that inconvenience with priority of setup metadata is likely to be fixed/clarified as a result of pypa/setuptools#1150 or its followup

**Comment by webknjaz** [comment]
Now this page feels complete: https://pypi.org/project/aiohttp-json-rpc

**Pull request merged**
