### PR TITLE
Make travis+tox tests great again and add a few cosmetic improvements

### PR DESCRIPTION
**Pull request by webknjaz**
Ref #9

Also:
* Add badges to README
* Include README into publicly visible distribution page
* Add pytest marker to distinguish django tests

### CODE REVIEW

**Comment by webknjaz** [comment]
https://travis-ci.org/webknjaz/aiohttp-json-rpc/builds/280427955

**Comment by fscherf** [comment]
Wow! Thats pretty amazing! Like you read my personal wishlist for this project

**Comment by webknjaz** [comment]
Yes, this marker applies to the whole module. If you want to mark specific function, decorate it with `@pytest.mark.django`

**Comment by webknjaz** [comment]
Oh, it's just a boilerplate. Lot's of my other projects have `AppVeyor` (windows CI) set up as well and that's why I bypass their typical env vars as well. This is how different tools like coveragepy detect whether they run within some CI.

**Comment by fscherf** [comment]
I don't like two things in this pr:

You have two very similar pytest calls in the tox.ini with only '-m not django' as difference. Can you make this a env variable?

I think i dont want to use pytest-sugar. Sure it looks nice but i want new dependencies which i dont need very bad

**Comment by webknjaz** [comment]
You can always push your changes to PR branch: github has this feature to enable PR author allowing write access to their branch for repo maintainers.

**Comment by webknjaz** [comment]
Regarding env vars: I was thinking about this and concluded this would be as ugly as lots for copy-pasted lines

**Comment by fscherf** [comment]
hm maybe you are right. I'll merge it with the copy-pasted lines and change it to env vars if it bothers me.

Do i need 'doctest_optionflags=ALLOW_UNICODE ELLIPSIS'?

**Comment by webknjaz** [comment]
You'll probably want to have this option at some point if you add some doctests

**Comment by webknjaz** [comment]
I've trying to make tox work with env vars for 20 min now with no success :(

**Comment by fscherf** [comment]
ok then i remove this hunk. This project has to be as easy to understand as possible, so no magic lines that are not necessary.
Don't bother, i'll take it without env vars :)

**Comment by webknjaz** [comment]
Thank you for being responsive :)

**Comment by webknjaz** [comment]
https://travis-ci.org/pengutronix/aiohttp-json-rpc
@fscherf it looks like you've disabled tests in Travis, you should enable them at this page

**Comment by webknjaz** [comment]
would you release new patch version to PYPI?

**Comment by fscherf** [comment]
Done! THX for the Makefile :)

**Comment by webknjaz** [comment]
It looks like you didn't include long description into distribution, I guess you used `setuptools<30.3`, right? If so, it didn't pick up metadata from `setup.cfg`.

Could you please upgrade setuptools and try again? Shall I include upgrading it into Makefile (or maybe move it all to tox to avoid depending on too many tools)?

**Comment by fscherf** [comment]
oh you are right! hm i think a upgrade target in the makefile would be great

**Comment by webknjaz** [comment]
What about tox? It might be beneficial to use it and isolate influence of changing environment with virtualenv

**Comment by fscherf** [comment]
I think tox is a good idea for this

**Comment by webknjaz** [comment]
Yea, I'm trying to make it work now, there's a strange issue I face currently.

**Comment by fscherf** [comment]
Do you need any help?

**Comment by webknjaz** [comment]
I've figured it out myself, thanks :)
I really dislike tox for complications it creates sometimes.

**Pull request merged**
